[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "maap-data-downloaders"
version = "1.0.0"
description = "OGC Application Package collection for downloading scientific data in NASA MAAP"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["src"]
