"""Build pystac Items, Collections, and Catalogs from downloaded files."""

from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pystac  # type: ignore[import]
from shapely.geometry import box, mapping  # type: ignore[import]


def create_stac_item(
    filepath: str | os.PathLike,
    metadata: dict[str, Any],
    collection_id: str,
) -> pystac.Item:
    """Build a STAC Item for a downloaded file.

    Args:
        filepath: Path to the local data file.
        metadata: Dict from file_utils.extract_metadata().
        collection_id: Parent collection identifier.

    Returns:
        A pystac.Item with geometry, datetime, bbox, assets, and properties.
    """
    path = Path(filepath)
    item_id = path.stem

    bbox = metadata.get("bbox") or [-180.0, -90.0, 180.0, 90.0]
    geometry = mapping(box(*bbox))

    start_str = metadata.get("time_coverage_start")
    end_str = metadata.get("time_coverage_end")
    item_datetime = _parse_datetime(start_str) or datetime.now(tz=timezone.utc)

    item = pystac.Item(
        id=item_id,
        geometry=geometry,
        bbox=bbox,
        datetime=item_datetime,
        properties={
            "title": metadata.get("title") or path.name,
            "datetime": item_datetime.isoformat(),
            **({"start_datetime": start_str} if start_str else {}),
            **({"end_datetime": end_str} if end_str else {}),
        },
    )

    item.add_asset(
        "data",
        pystac.Asset(
            href=str(path.resolve()),
            media_type=_media_type(path),
            roles=["data"],
            title=metadata.get("title") or path.name,
        ),
    )

    item.collection_id = collection_id
    return item


def build_catalog(
    items: list[pystac.Item],
    output_dir: str | os.PathLike,
    collection_id: str,
) -> None:
    """Write a STAC catalog tree to output_dir.

    Output structure:
        output_dir/
          catalog.json
          {collection_id}/
            collection.json
            items/
              {item_id}.json
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    slug = _slugify(collection_id)

    collection = pystac.Collection(
        id=slug,
        description=f"Data downloaded into collection '{collection_id}'",
        extent=pystac.Extent(
            spatial=pystac.SpatialExtent(bboxes=[[-180, -90, 180, 90]]),
            temporal=pystac.TemporalExtent(intervals=[[None, None]]),
        ),
    )
    for item in items:
        collection.add_item(item)

    catalog = pystac.Catalog(
        id="maap-data-downloaders-catalog",
        description="Root STAC catalog generated by maap-data-downloaders",
        catalog_type=pystac.CatalogType.SELF_CONTAINED,
    )
    catalog.add_child(collection)

    catalog.normalize_hrefs(str(out))
    catalog.save(catalog_type=pystac.CatalogType.SELF_CONTAINED)


def _parse_datetime(value: str | None) -> datetime | None:
    if not value:
        return None
    formats = [
        "%Y-%m-%dT%H:%M:%S.%fZ",
        "%Y-%m-%dT%H:%M:%SZ",
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d",
        "%Y%j",   # day-of-year
        "%Y%m%d",
    ]
    for fmt in formats:
        try:
            return datetime.strptime(value.strip(), fmt).replace(tzinfo=timezone.utc)
        except ValueError:
            continue
    return None


def _media_type(path: Path) -> str:
    ext = path.suffix.lower()
    return {
        ".nc": "application/x-netcdf",
        ".nc4": "application/x-netcdf",
        ".h5": "application/x-hdf5",
        ".hdf5": "application/x-hdf5",
        ".hdf": "application/x-hdf5",
        ".tif": "image/tiff; application=geotiff",
        ".tiff": "image/tiff; application=geotiff",
    }.get(ext, "application/octet-stream")


def _slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
